load("//Carthage:carthage.bzl" ,"carthage_deps")

apple_library(
        name = "CarthageDeps",
        visibility = [
            "PUBLIC"
        ],
        swift_version = "5",
        configs = {},
        srcs = [],
        preferred_linkage="shared",
        deps = carthage_deps()
)