//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: todo.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import Foundation
import GRPC
import NIO
import NIOHTTP1
import SwiftProtobuf


/// Usage: instantiate Pb_TodoServiceServiceClient, then call methods of this protocol to make API calls.
public protocol Pb_TodoServiceService {
  func list(_ request: SwiftProtobuf.Google_Protobuf_Empty, callOptions: CallOptions?) -> UnaryCall<SwiftProtobuf.Google_Protobuf_Empty, Pb_TodoList>
  func get(_ request: Pb_TodoIdentifier, callOptions: CallOptions?) -> UnaryCall<Pb_TodoIdentifier, Pb_Todo>
  func create(_ request: Pb_TodoCreate, callOptions: CallOptions?) -> UnaryCall<Pb_TodoCreate, Pb_Todo>
  func update(_ request: Pb_Todo, callOptions: CallOptions?) -> UnaryCall<Pb_Todo, Pb_Todo>
  func delete(_ request: Pb_TodoIdentifier, callOptions: CallOptions?) -> UnaryCall<Pb_TodoIdentifier, Pb_Status>
}

public final class Pb_TodoServiceServiceClient: GRPCClient, Pb_TodoServiceService {
  public let connection: ClientConnection
  public var defaultCallOptions: CallOptions

  /// Creates a client for the pb.TodoService service.
  ///
  /// - Parameters:
  ///   - connection: `ClientConnection` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  public init(connection: ClientConnection, defaultCallOptions: CallOptions = CallOptions()) {
    self.connection = connection
    self.defaultCallOptions = defaultCallOptions
  }

  /// Asynchronous unary call to List.
  ///
  /// - Parameters:
  ///   - request: Request to send to List.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func list(_ request: SwiftProtobuf.Google_Protobuf_Empty, callOptions: CallOptions? = nil) -> UnaryCall<SwiftProtobuf.Google_Protobuf_Empty, Pb_TodoList> {
    return self.makeUnaryCall(path: "/pb.TodoService/List",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

  /// Asynchronous unary call to Get.
  ///
  /// - Parameters:
  ///   - request: Request to send to Get.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func get(_ request: Pb_TodoIdentifier, callOptions: CallOptions? = nil) -> UnaryCall<Pb_TodoIdentifier, Pb_Todo> {
    return self.makeUnaryCall(path: "/pb.TodoService/Get",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

  /// Asynchronous unary call to Create.
  ///
  /// - Parameters:
  ///   - request: Request to send to Create.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func create(_ request: Pb_TodoCreate, callOptions: CallOptions? = nil) -> UnaryCall<Pb_TodoCreate, Pb_Todo> {
    return self.makeUnaryCall(path: "/pb.TodoService/Create",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

  /// Asynchronous unary call to Update.
  ///
  /// - Parameters:
  ///   - request: Request to send to Update.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func update(_ request: Pb_Todo, callOptions: CallOptions? = nil) -> UnaryCall<Pb_Todo, Pb_Todo> {
    return self.makeUnaryCall(path: "/pb.TodoService/Update",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

  /// Asynchronous unary call to Delete.
  ///
  /// - Parameters:
  ///   - request: Request to send to Delete.
  ///   - callOptions: Call options; `self.defaultCallOptions` is used if `nil`.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  public func delete(_ request: Pb_TodoIdentifier, callOptions: CallOptions? = nil) -> UnaryCall<Pb_TodoIdentifier, Pb_Status> {
    return self.makeUnaryCall(path: "/pb.TodoService/Delete",
                              request: request,
                              callOptions: callOptions ?? self.defaultCallOptions)
  }

}

/// To build a server, implement a class that conforms to this protocol.
public protocol Pb_TodoServiceProvider: CallHandlerProvider {
  func list(request: SwiftProtobuf.Google_Protobuf_Empty, context: StatusOnlyCallContext) -> EventLoopFuture<Pb_TodoList>
  func get(request: Pb_TodoIdentifier, context: StatusOnlyCallContext) -> EventLoopFuture<Pb_Todo>
  func create(request: Pb_TodoCreate, context: StatusOnlyCallContext) -> EventLoopFuture<Pb_Todo>
  func update(request: Pb_Todo, context: StatusOnlyCallContext) -> EventLoopFuture<Pb_Todo>
  func delete(request: Pb_TodoIdentifier, context: StatusOnlyCallContext) -> EventLoopFuture<Pb_Status>
}

extension Pb_TodoServiceProvider {
  public var serviceName: String { return "pb.TodoService" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  public func handleMethod(_ methodName: String, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "List":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.list(request: request, context: context)
        }
      }

    case "Get":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.get(request: request, context: context)
        }
      }

    case "Create":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.create(request: request, context: context)
        }
      }

    case "Update":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.update(request: request, context: context)
        }
      }

    case "Delete":
      return UnaryCallHandler(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.delete(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}

